### ISSUE TITLE
I need some help. Why does such a simple program have an error. I've been troubled for a long time

### ISSUE THREAD

**Issue by 2424719479** [gam6itko/ozon-seller#81]
![错误](https://github.com/gam6itko/ozon-seller/assets/94888456/1b321c7f-639a-41b7-9038-3556a1dcddde)
I need some help. Why does such a simple program have an error. I've been troubled for a long time

**Comment by downace** [comment]
Your issue is not related to this library.

<details>
<summary>But...</summary>

AFAIK, by defeault `requests.post` will send `data` as form-encoded body, e.g. `chat_id=...&text=...`.
But Ozon API expects request body as JSON.
You need to pass a body as JSON explicitly: `data=json.dumps(body)` or `json=body`
You may also need to pass `Content-Type: application/json` header.
</details>

**Comment by gam6itko** [comment]
this library is not related to Python
